# Generated by Django 4.2.11 on 2024-04-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_collaboraterequest_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboraterequest',
            old_name='featured_image',
            new_name='profile_image',
        ),
    ]
